# vid2md.ps1 - Convert a YouTube URL to a markdown image-link and copy it to clipboard.
#
# Modes:
#   No argument / any non-.url file / folder  -> opens the URL input UI
#   .url Internet Shortcut path               -> silently reads URL from file and converts
#   YouTube URL string directly               -> silently converts (CLI mode)
#
# On success: markdown is on the clipboard and a Windows toast notification appears.

param(
    [string]$Target = ""
)

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

# EM_SETCUEBANNER: native Win32 placeholder text for a TextBox
Add-Type -TypeDefinition @'
using System;
using System.Runtime.InteropServices;
public static class TextBoxHelper {
    [DllImport("user32.dll", CharSet = CharSet.Unicode)]
    static extern IntPtr SendMessage(IntPtr hWnd, int msg, bool wParam, string lParam);
    public static void SetPlaceholder(IntPtr handle, string text) {
        SendMessage(handle, 0x1501, false, text);
    }
}
'@

# ---------------------------------------------------------------------------
# Toast notification
# ---------------------------------------------------------------------------
function Show-Toast([string]$heading, [string]$body) {
    try {
        [void][Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType=WindowsRuntime]
        [void][Windows.Data.Xml.Dom.XmlDocument, Windows.Data.Xml.Dom.XmlDocument, ContentType=WindowsRuntime]
        $xml = New-Object Windows.Data.Xml.Dom.XmlDocument
        $xml.LoadXml("<toast duration=`"short`"><visual><binding template=`"ToastGeneric`"><text>$heading</text><text>$body</text></binding></visual></toast>")
        $toast = [Windows.UI.Notifications.ToastNotification]::new($xml)
        [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier("vid2md").Show($toast)
    } catch {}
}

# ---------------------------------------------------------------------------
# Silent conversion: API call -> clipboard -> toast
# Throws on any error so callers can handle it.
# ---------------------------------------------------------------------------
function Invoke-Conversion([string]$url) {
    $body     = @{ url = $url } | ConvertTo-Json -Compress
    $response = Invoke-RestMethod `
        -Method Post `
        -Uri "https://quirky-squirrel-220.convex.site/api/markdown" `
        -Body $body `
        -ContentType "application/json" `
        -ErrorAction Stop

    if (-not $response.markdown) { throw "API returned an empty markdown field." }

    Set-Clipboard -Value $response.markdown
    $title = if ($response.title) { $response.title } else { "YouTube Video" }
    Show-Toast "Copied to clipboard" $title
    return $response
}

# ---------------------------------------------------------------------------
# UI
# ---------------------------------------------------------------------------
function Show-UI([string]$preset = "") {

    # -- Form --
    $form                 = New-Object System.Windows.Forms.Form
    $form.Text            = "Video to Markdown"
    $form.ClientSize      = New-Object System.Drawing.Size(420, 140)
    $form.StartPosition   = "CenterScreen"
    $form.TopMost         = $true
    $form.FormBorderStyle = "FixedSingle"
    $form.MaximizeBox     = $false
    $form.MinimizeBox     = $false
    $form.BackColor       = [System.Drawing.Color]::FromArgb(248, 248, 248)
    $form.Font            = New-Object System.Drawing.Font("Segoe UI", 10)

    # Form icon (generated by install.ps1 into LOCALAPPDATA)
    $icoPath = "$env:LOCALAPPDATA\mike-rosoft\icons\vid2md.ico"
    if (Test-Path $icoPath) {
        try { $form.Icon = New-Object System.Drawing.Icon($icoPath) } catch {}
    }

    # -- Instruction label --
    $lblInstruction            = New-Object System.Windows.Forms.Label
    $lblInstruction.Text       = "Paste a YouTube URL below, then press Enter"
    $lblInstruction.Location   = New-Object System.Drawing.Point(12, 12)
    $lblInstruction.Size       = New-Object System.Drawing.Size(396, 18)
    $lblInstruction.ForeColor  = [System.Drawing.Color]::FromArgb(90, 90, 90)
    $lblInstruction.Font       = New-Object System.Drawing.Font("Segoe UI", 9)

    # -- URL text box --
    $txtUrl                    = New-Object System.Windows.Forms.TextBox
    $txtUrl.Location           = New-Object System.Drawing.Point(12, 38)
    $txtUrl.Size               = New-Object System.Drawing.Size(396, 26)
    $txtUrl.Text               = $preset
    $txtUrl.SelectionStart     = $txtUrl.Text.Length

    # -- Convert button --
    $btnConvert                       = New-Object System.Windows.Forms.Button
    $btnConvert.Text                  = "Convert"
    $btnConvert.Location              = New-Object System.Drawing.Point(12, 76)
    $btnConvert.Size                  = New-Object System.Drawing.Size(396, 32)
    $btnConvert.BackColor             = [System.Drawing.Color]::FromArgb(0, 120, 212)
    $btnConvert.ForeColor             = [System.Drawing.Color]::White
    $btnConvert.FlatStyle             = "Flat"
    $btnConvert.FlatAppearance.BorderSize = 0

    # -- Progress bar (marquee, visible while converting) --
    $pbLoading                 = New-Object System.Windows.Forms.ProgressBar
    $pbLoading.Location        = New-Object System.Drawing.Point(12, 120)
    $pbLoading.Size            = New-Object System.Drawing.Size(396, 8)
    $pbLoading.Style           = "Marquee"
    $pbLoading.MarqueeAnimationSpeed = 25
    $pbLoading.Visible         = $false

    # -- Status label (shown on success / error inline) --
    $lblStatus                 = New-Object System.Windows.Forms.Label
    $lblStatus.Location        = New-Object System.Drawing.Point(12, 116)
    $lblStatus.Size            = New-Object System.Drawing.Size(396, 18)
    $lblStatus.TextAlign       = "MiddleCenter"
    $lblStatus.Font            = New-Object System.Drawing.Font("Segoe UI", 9)
    $lblStatus.Visible         = $false

    $form.AcceptButton = $btnConvert

    $form.Add_Shown({
        [TextBoxHelper]::SetPlaceholder($txtUrl.Handle, "https://youtu.be/...")
        $txtUrl.Focus()
        if ($txtUrl.Text.Length -gt 0) { $txtUrl.SelectAll() }
    })

    # -- Button click: validate, spin up a PS runspace for the HTTP call, poll with a timer --
    $btnConvert.Add_Click({
        $url = $txtUrl.Text.Trim()

        if ($url -notmatch "youtube\.com|youtu\.be") {
            [System.Windows.Forms.MessageBox]::Show(
                "Please enter a valid YouTube URL.",
                "Video to Markdown",
                [System.Windows.Forms.MessageBoxButtons]::OK,
                [System.Windows.Forms.MessageBoxIcon]::Warning
            ) | Out-Null
            $txtUrl.SelectAll()
            $txtUrl.Focus()
            return
        }

        $btnConvert.Enabled = $false
        $btnConvert.Text    = "Converting..."
        $lblStatus.Visible  = $false
        $pbLoading.Visible  = $true

        # Spin up a dedicated runspace so Invoke-RestMethod has a PS environment.
        # BackgroundWorker.DoWork fires on a threadpool thread with no runspace - that's
        # why it failed. This approach creates one explicitly.
        $iss = [System.Management.Automation.Runspaces.InitialSessionState]::CreateDefault()
        $script:bgRs = [System.Management.Automation.Runspaces.RunspaceFactory]::CreateRunspace($iss)
        $script:bgRs.Open()
        $script:bgPs = [System.Management.Automation.PowerShell]::Create()
        $script:bgPs.Runspace = $script:bgRs
        [void]$script:bgPs.AddScript({
            param($u)
            $b = @{ url = $u } | ConvertTo-Json -Compress
            Invoke-RestMethod -Method Post `
                -Uri "https://quirky-squirrel-220.convex.site/api/markdown" `
                -Body $b -ContentType "application/json" -ErrorAction Stop
        }).AddArgument($url)
        $script:bgAsync = $script:bgPs.BeginInvoke()

        # Poll every 150 ms on the UI thread - this keeps the marquee animating
        $script:pollTimer = New-Object System.Windows.Forms.Timer
        $script:pollTimer.Interval = 150
        $script:pollTimer.Add_Tick({
            if (-not $script:bgAsync.IsCompleted) { return }

            $script:pollTimer.Stop()
            $pbLoading.Visible = $false

            if ($script:bgPs.HadErrors) {
                $errRec = $script:bgPs.Streams.Error | Select-Object -First 1
                $errMsg = $errRec.Exception.Message
                # Try to surface the API's own error message from the response body
                $webEx = $errRec.Exception.InnerException
                if ($webEx -and $webEx.Response) {
                    try {
                        $sr   = New-Object System.IO.StreamReader($webEx.Response.GetResponseStream())
                        $j    = $sr.ReadToEnd() | ConvertFrom-Json -ErrorAction SilentlyContinue
                        if ($j.error) { $errMsg = $j.error }
                    } catch {}
                }
                $script:bgRs.Close(); $script:bgPs.Dispose()
                [System.Windows.Forms.MessageBox]::Show(
                    "API request failed:`n$errMsg",
                    "Video to Markdown",
                    [System.Windows.Forms.MessageBoxButtons]::OK,
                    [System.Windows.Forms.MessageBoxIcon]::Error
                ) | Out-Null
                $btnConvert.Enabled = $true
                $btnConvert.Text    = "Convert"
                return
            }

            $response = ($script:bgPs.EndInvoke($script:bgAsync))[0]
            $script:bgRs.Close(); $script:bgPs.Dispose()

            if (-not $response.markdown) {
                [System.Windows.Forms.MessageBox]::Show(
                    "API returned an empty markdown field.",
                    "Video to Markdown",
                    [System.Windows.Forms.MessageBoxButtons]::OK,
                    [System.Windows.Forms.MessageBoxIcon]::Error
                ) | Out-Null
                $btnConvert.Enabled = $true
                $btnConvert.Text    = "Convert"
                return
            }

            Set-Clipboard -Value $response.markdown
            $videoTitle = if ($response.title) { $response.title } else { "YouTube Video" }
            Show-Toast "Copied to clipboard" $videoTitle

            $lblStatus.Text      = "Copied to clipboard!"
            $lblStatus.ForeColor = [System.Drawing.Color]::FromArgb(16, 124, 16)
            $lblStatus.Visible   = $true
            $btnConvert.Text     = "Done"

            $closeTimer          = New-Object System.Windows.Forms.Timer
            $closeTimer.Interval = 1500
            $closeTimer.Add_Tick({ $form.Close() })
            $closeTimer.Start()
        })
        $script:pollTimer.Start()
    })

    $form.Controls.AddRange(@($lblInstruction, $txtUrl, $btnConvert, $pbLoading, $lblStatus))
    [void]$form.ShowDialog()
}

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if ($Target -match "^https?://") {
    # CLI silent mode
    try {
        Invoke-Conversion $Target.Trim()
    } catch {
        [System.Windows.Forms.MessageBox]::Show(
            "Error: $($_.Exception.Message)",
            "Video to Markdown",
            [System.Windows.Forms.MessageBoxButtons]::OK,
            [System.Windows.Forms.MessageBoxIcon]::Error
        ) | Out-Null
        exit 1
    }

} elseif ($Target -and (Test-Path $Target) -and ([System.IO.Path]::GetExtension($Target).ToLower() -eq ".url")) {
    # .url Internet Shortcut - silent mode, no UI
    $urlLine = (Get-Content $Target -ErrorAction SilentlyContinue) |
               Where-Object { $_ -match "^URL=" } | Select-Object -First 1
    if (-not $urlLine) {
        [System.Windows.Forms.MessageBox]::Show(
            "Could not find a URL in:`n$Target",
            "Video to Markdown",
            [System.Windows.Forms.MessageBoxButtons]::OK,
            [System.Windows.Forms.MessageBoxIcon]::Error
        ) | Out-Null
        exit 1
    }
    try {
        Invoke-Conversion (($urlLine -replace "^URL=", "").Trim())
    } catch {
        [System.Windows.Forms.MessageBox]::Show(
            "Error: $($_.Exception.Message)",
            "Video to Markdown",
            [System.Windows.Forms.MessageBoxButtons]::OK,
            [System.Windows.Forms.MessageBoxIcon]::Error
        ) | Out-Null
        exit 1
    }

} else {
    # UI mode: no arg, or right-click on any file/folder
    # Pre-fill from clipboard if it already has a YouTube URL
    $clip   = (Get-Clipboard -ErrorAction SilentlyContinue) -as [string]
    $preset = if ($clip -match "youtube\.com|youtu\.be") { $clip.Trim() } else { "" }
    Show-UI $preset
}
